services:
  app:
    build: .
    container_name: labinv_app
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - labinv_images:/app/images

volumes:
  labinv_images:
